"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { ArrowLeft, Check, CircleAlert, LoaderCircle } from "lucide-react";

type Detail = { requestNumber: string; requesterName: string; status: string; createdAt: string; updatedAt: string; patientName: string | null; medications: Array<{ commercialName: string; activeIngredient: string; concentration: string; tabletQuantity: number }>; hasQuote: boolean; quote: { quoteNumber: string | null; version: number; total: string | number | null; validUntil: string | null; items: Array<{ productName: string; activeIngredient: string | null; concentration: string | null; quantity: number; unitPrice: string | number | null; totalPrice: string | number | null }> } | null };
const date = (value: string) => new Intl.DateTimeFormat("es-CL", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const labels: Record<string, string> = { QUOTED: "Cotizada", AWAITING_DECISION: "Esperando respuesta", ACCEPTED: "Aceptada", SHIPPING: "En despacho", COMPLETED: "Finalizada", REJECTED: "Rechazada", CANCELLED: "Cancelada" };

export default function TrackingDetail({ requestNumber }: { requestNumber: string }) {
  const [detail, setDetail] = useState<Detail | null>(null); const [error, setError] = useState(""); const [comment, setComment] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [feedback, setFeedback] = useState("");
  const submitComment = async () => { if (!comment.trim()) return setFeedback("Escribe un comentario antes de enviarlo."); setSaving(true); setFeedback(""); try { const token = sessionStorage.getItem(`axessia-tracking-${requestNumber.toUpperCase()}`); const response = await fetch("/api/tracking/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, action: "comment", comment }) }); if (!response.ok) throw new Error((await response.json()).error || "No fue posible enviar el comentario."); setComment(""); setFeedback("Tu comentario fue enviado al equipo AXESSIA."); } catch (cause) { setFeedback(cause instanceof Error ? cause.message : "No fue posible enviar el comentario."); } finally { setSaving(false); } };
  // The effect owns the protected detail request and its loading lifecycle.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { const token = sessionStorage.getItem(`axessia-tracking-${requestNumber.toUpperCase()}`); if (!token) { setError("Vuelve a /seguimiento y valida tu solicitud para continuar."); setLoading(false); return; } fetch(`/api/tracking/detail?token=${encodeURIComponent(token)}`).then(async (response) => { if (!response.ok) throw new Error("La sesión de seguimiento expiró."); setDetail(await response.json() as Detail); }).catch((cause) => setError(cause instanceof Error ? cause.message : "No fue posible cargar la cotización.")).finally(() => setLoading(false)); }, [requestNumber]);
  const decide = async (action: "accept" | "reject") => { if (!detail?.quote || !window.confirm(action === "accept" ? "¿Confirmas que deseas aceptar esta cotización?" : "¿Confirmas que deseas rechazar esta cotización?")) return; setSaving(true); setFeedback(""); try { const token = sessionStorage.getItem(`axessia-tracking-${requestNumber.toUpperCase()}`); const response = await fetch("/api/tracking/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, action, comment }) }); if (!response.ok) throw new Error((await response.json()).error || "No fue posible registrar la decisión."); setFeedback(action === "accept" ? "Tu aceptación fue registrada." : "Tu rechazo fue registrado."); setDetail({ ...detail, status: action === "accept" ? "ACCEPTED" : "REJECTED", hasQuote: false, quote: null }); } catch (cause) { setFeedback(cause instanceof Error ? cause.message : "No fue posible registrar la decisión."); } finally { setSaving(false); } };
  if (loading) return <main className="mx-auto max-w-5xl px-5 py-20 text-center text-[var(--text-secondary)]"><LoaderCircle className="mx-auto animate-spin" aria-label="Cargando" /></main>;
  if (error || !detail) return <main className="mx-auto max-w-2xl px-5 py-20 text-center"><CircleAlert className="mx-auto text-red-600" /><p className="mt-4 font-semibold text-[var(--navy)]">{error || "No fue posible cargar el seguimiento."}</p><Link className="mt-6 inline-flex items-center gap-2 font-bold text-[var(--blue)]" href="/seguimiento"><ArrowLeft size={17} /> Volver al seguimiento</Link></main>;
  return <main className="mx-auto max-w-5xl px-5 py-12 sm:px-8"><Link className="inline-flex items-center gap-2 text-sm font-bold text-[var(--blue)]" href="/seguimiento"><ArrowLeft size={17} /> Volver al seguimiento</Link><motion.div className="mt-8" initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}><p className="eyebrow">Detalle protegido</p><div className="mt-2 flex flex-wrap items-center justify-between gap-4"><h1 className="text-3xl font-bold text-[var(--navy)]">Solicitud {detail.requestNumber}</h1><span className="rounded-full bg-[rgba(8,127,213,0.1)] px-3 py-2 text-sm font-bold text-[var(--blue)]">{labels[detail.status] || detail.status}</span></div><p className="mt-3 text-sm text-[var(--text-secondary)]">Creada {date(detail.createdAt)} · Actualizada {date(detail.updatedAt)}</p>
    <section className="card-surface mt-8 rounded-2xl p-5 sm:p-8"><h2 className="text-xl font-bold text-[var(--navy)]">Lo que solicitaste</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead className="text-[var(--text-secondary)]"><tr><th className="pb-3">Medicamento</th><th className="pb-3">Principio activo</th><th className="pb-3">Concentración</th><th className="pb-3 text-right">Cantidad</th></tr></thead><tbody>{detail.medications.map((item) => <tr className="border-t border-[var(--border)]" key={`${item.commercialName}-${item.concentration}`}><td className="py-3 font-semibold text-[var(--navy)]">{item.commercialName}</td><td className="py-3 text-[var(--text-secondary)]">{item.activeIngredient}</td><td className="py-3 text-[var(--text-secondary)]">{item.concentration}</td><td className="py-3 text-right text-[var(--text-secondary)]">{item.tabletQuantity}</td></tr>)}</tbody></table></div></section>
    {detail.quote ? <section className="card-surface mt-6 rounded-2xl p-5 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div><p className="eyebrow">Propuesta AXESSIA</p><h2 className="mt-2 text-xl font-bold text-[var(--navy)]">Cotización {detail.quote.quoteNumber || `versión ${detail.quote.version}`}</h2></div>{detail.quote.validUntil && <p className="text-sm font-semibold text-[var(--text-secondary)]">Válida hasta {date(detail.quote.validUntil)}</p>}</div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="text-[var(--text-secondary)]"><tr><th className="pb-3">Producto ofrecido</th><th className="pb-3">Cantidad</th><th className="pb-3 text-right">Valor unitario</th><th className="pb-3 text-right">Total</th></tr></thead><tbody>{detail.quote.items.map((item) => <tr className="border-t border-[var(--border)]" key={`${item.productName}-${item.quantity}`}><td className="py-3 font-semibold text-[var(--navy)]">{item.productName}<small className="block font-normal text-[var(--text-secondary)]">{item.activeIngredient} {item.concentration}</small></td><td className="py-3 text-[var(--text-secondary)]">{item.quantity}</td><td className="py-3 text-right text-[var(--text-secondary)]">{item.unitPrice ?? "-"}</td><td className="py-3 text-right font-semibold text-[var(--navy)]">{item.totalPrice ?? "-"}</td></tr>)}</tbody></table></div><p className="mt-6 text-right text-xl font-bold text-[var(--navy)]">Total: {detail.quote.total ?? "Por confirmar"}</p><label className="mt-6 block text-sm font-bold text-[var(--navy)]" htmlFor="tracking-comment">Comentario o consulta <span className="font-normal text-[var(--text-secondary)]">(opcional)</span></label><textarea id="tracking-comment" className="mt-2 min-h-24 w-full rounded-xl border border-[var(--border)] p-3 text-sm outline-none focus:border-[var(--blue)]" value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Escribe una consulta para nuestro equipo." /><div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={saving} onClick={() => decide("accept")} className="inline-flex items-center gap-2 rounded-full bg-[var(--brand-gradient)] px-5 py-3 text-sm font-bold text-white"><Check size={17} /> Aceptar cotización</button><button type="button" disabled={saving} onClick={() => decide("reject")} className="rounded-full border border-[var(--blue)] px-5 py-3 text-sm font-bold text-[var(--blue)]">Rechazar cotización</button></div>{feedback && <p className="mt-4 text-sm font-semibold text-[var(--blue)]" role="status">{feedback}</p>}</section> : <p className="mt-6 rounded-2xl border border-[var(--border)] bg-white p-5 text-sm font-semibold text-[var(--text-secondary)]">Esta solicitud no tiene una cotización disponible para decisión.</p>}
    <p className="mt-8 text-center text-sm text-[var(--text-secondary)]">¿Quieres un seguimiento más simple? <Link className="font-bold text-[var(--blue)]" href="/registrarme">Crea tu cuenta AXESSIA</Link>. Es opcional.</p></motion.div></main>;
}
