"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, Download, FileSpreadsheet, FileText, RefreshCw } from "lucide-react";
import PageHeader from "../components/PageHeader";

type ReportType = "requests" | "customers" | "suppliers" | "quotes" | "sales" | "executives";
type ReportResponse = { title: string; rows: Record<string, string | number>[]; count: number };
type ExecutiveOption = { id: string; firstName: string; lastName: string };
const reportTypes: { value: ReportType; label: string }[] = [{ value: "requests", label: "Solicitudes" }, { value: "customers", label: "Clientes" }, { value: "suppliers", label: "Proveedores" }, { value: "quotes", label: "Cotizaciones" }, { value: "sales", label: "Ventas pagadas" }, { value: "executives", label: "Por ejecutivo" }];
const statusOptions: Record<ReportType, string[]> = { requests: ["RECEIVED", "SOURCING", "QUOTED", "AWAITING_DECISION", "ACCEPTED", "SHIPPING", "REJECTED", "CANCELLED", "COMPLETED"], customers: [], suppliers: [], quotes: ["DRAFT", "READY", "SENT", "ACCEPTED", "REJECTED", "EXPIRED", "VOIDED"], sales: [], executives: [] };

export default function ReportsView() {
  const [type, setType] = useState<ReportType>("requests"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [status, setStatus] = useState(""); const [executiveId, setExecutiveId] = useState(""); const [executives, setExecutives] = useState<ExecutiveOption[]>([]); const [data, setData] = useState<ReportResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const query = useMemo(() => { const params = new URLSearchParams({ type }); if (from) params.set("from", from); if (to) params.set("to", to); if (status) params.set("status", status); if (executiveId) params.set("executiveId", executiveId); return params; }, [type, from, to, status, executiveId]);
  const [executiveFilter, setExecutiveFilter] = useState("");
  useEffect(() => { if (type !== "executives" || executives.length) return; void fetch("/api/users?role=Ejecutivo&limit=50").then((response) => response.ok ? response.json() as Promise<{ users: ExecutiveOption[] }> : null).then((result) => { if (result) setExecutives(result.users); }).catch(() => undefined); }, [type, executives.length]);
  const load = async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/reports?${query}`, { cache: "no-store" }); const result = await response.json() as ReportResponse & { error?: string }; if (!response.ok) throw new Error(result.error || "No fue posible cargar el reporte."); setData(result); } catch (err) { setError(err instanceof Error ? err.message : "No fue posible cargar el reporte."); } finally { setLoading(false); } };
  useEffect(() => { void load(); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query]);
  const download = (format: "csv" | "xlsx" | "pdf") => { window.location.href = `/api/reports?${query}&format=${format}`; };
  const headers = data?.rows[0] ? Object.keys(data.rows[0]) : [];
  return <div><PageHeader icon={BarChart3} eyebrow="Análisis" title="Reportes" description="Consulta registros operativos y descárgalos sin guardar copias en la base de datos." />
    <section className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm">
      {type === "sales" && <p className="mb-4 rounded-lg bg-emerald-50 px-4 py-3 text-xs font-semibold text-emerald-800">Este reporte solo incluye cotizaciones aceptadas con al menos un pago confirmado. La fecha usada para filtrar es la fecha de pago. El costo queda como “No registrado” hasta incorporarlo al sistema.</p>}
      <div className="grid gap-4 md:grid-cols-4"><label className="text-xs font-bold text-[var(--navy)]">Tipo de registros<select className="field-input mt-2" value={type} onChange={(event) => { setType(event.target.value as ReportType); setStatus(""); }}>{reportTypes.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label><label className="text-xs font-bold text-[var(--navy)]">Desde<input className="field-input mt-2" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-xs font-bold text-[var(--navy)]">Hasta<input className="field-input mt-2" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label>{statusOptions[type].length > 0 && <label className="text-xs font-bold text-[var(--navy)]">Estado<select className="field-input mt-2" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{statusOptions[type].map((option) => <option key={option} value={option}>{option}</option>)}</select></label>}{type === "executives" && <label className="text-xs font-bold text-[var(--navy)]">Ejecutivo<select className="field-input mt-2" value={executiveFilter} onChange={(event) => { setExecutiveFilter(event.target.value); setExecutiveId(event.target.value); }}><option value="">Todos</option>{executives.map((executive) => <option key={executive.id} value={executive.id}>{executive.firstName} {executive.lastName}</option>)}<option value="unassigned">Sin asignar</option></select></label>}</div>
      <div className="mt-5 flex flex-wrap items-center gap-2 border-t border-[var(--border)] pt-4"><span className="mr-2 text-sm font-bold text-[var(--navy)]">Descargar:</span><button className="inline-flex items-center gap-2 rounded-lg bg-[var(--navy)] px-3 py-2 text-xs font-bold text-white" onClick={() => download("csv")}><Download className="h-4 w-4" />CSV</button><button className="inline-flex items-center gap-2 rounded-lg bg-[#217346] px-3 py-2 text-xs font-bold text-white" onClick={() => download("xlsx")}><FileSpreadsheet className="h-4 w-4" />Excel / Sheets</button><button className="inline-flex items-center gap-2 rounded-lg bg-[#b42318] px-3 py-2 text-xs font-bold text-white" onClick={() => download("pdf")}><FileText className="h-4 w-4" />PDF</button><button className="ml-auto inline-flex items-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-bold text-[var(--navy)]" onClick={() => void load()}><RefreshCw className="h-4 w-4" />Actualizar</button></div>
    </section>
    <section className="mt-5 overflow-hidden rounded-2xl border border-[var(--border)] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[var(--border)] px-5 py-4"><div><h2 className="font-display text-lg font-extrabold text-[var(--navy)]">{data?.title ?? "Registros"}</h2><p className="text-xs text-[var(--text-secondary)]">{loading ? "Cargando…" : `${data?.count ?? 0} registros encontrados`}</p></div></div>{error ? <p className="p-8 text-center text-sm font-semibold text-red-600">{error}</p> : data?.rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-[var(--background)] text-[var(--text-secondary)]"><tr>{headers.map((header) => <th key={header} className="px-5 py-3 font-bold">{header}</th>)}</tr></thead><tbody>{data.rows.map((row, index) => <tr key={index} className="border-t border-[var(--border)]">{headers.map((header) => <td key={header} className="px-5 py-3 text-[var(--navy)]">{String(row[header] ?? "—")}</td>)}</tr>)}</tbody></table></div> : <p className="p-10 text-center text-sm text-[var(--text-secondary)]">{loading ? "Cargando registros…" : "No hay registros para los filtros seleccionados."}</p>}</section>
  </div>;
}
